<?php

declare(strict_types=1);

use Core\Http\URL;

/**
 * @var array<int,array<string,mixed>> $incidents
 * @var string|null $success
 * @var string|null $error
 */

$title = 'Incidents';

$incidents = $incidents ?? [];

$open = 0;
$resolved = 0;

foreach ($incidents as $incident) {

    if (
        (string) (
            $incident['status']
            ?? ''
        ) === 'open'
    ) {
        $open++;
    } else {
        $resolved++;
    }
}

$total = count($incidents);

ob_start();
?>

<div class="page-header">

    <div>

        <h1 class="page-title">
            Incidents
        </h1>

        <p class="page-subtitle">
            Monitor and review availability incidents affecting managed devices.
        </p>

    </div>

</div>


<?php if (!empty($success)): ?>

    <div class="alert alert-success">

        <?= htmlspecialchars(
            $success,
            ENT_QUOTES,
            'UTF-8'
        ) ?>

    </div>

<?php endif; ?>


<?php if (!empty($error)): ?>

    <div class="alert alert-error">

        <?= htmlspecialchars(
            $error,
            ENT_QUOTES,
            'UTF-8'
        ) ?>

    </div>

<?php endif; ?>


<div
    style="
        display:grid;
        grid-template-columns:
            repeat(auto-fit,minmax(180px,1fr));
        gap:15px;
        margin-bottom:25px;
    "
>

    <div class="dashboard-panel">

        <div class="panel-header">

            <div>

                <h2 id="incident-count-total">
                    <?= $total ?>
                </h2>

                <p>
                    Total Incidents
                </p>

            </div>

        </div>

    </div>


    <div class="dashboard-panel">

        <div class="panel-header">

            <div>

                <h2 id="incident-count-open">
                    <?= $open ?>
                </h2>

                <p>
                    Open
                </p>

            </div>

        </div>

    </div>


    <div class="dashboard-panel">

        <div class="panel-header">

            <div>

                <h2 id="incident-count-resolved">
                    <?= $resolved ?>
                </h2>

                <p>
                    Resolved
                </p>

            </div>

        </div>

    </div>

</div>


<section class="dashboard-panel">

    <div class="panel-header">

        <div>

            <h2>
                Monitoring Incidents
            </h2>

            <p>
                Availability incidents generated by the monitoring engine.
            </p>

        </div>

    </div>


    <?php if ($incidents === []): ?>

        <div class="empty-state">

            <div class="empty-state-icon">
                ✓
            </div>

            <h3>
                No incidents recorded
            </h3>

            <p>
                Monitoring incidents will appear here when managed devices
                experience availability problems.
            </p>

            <p>

                <a
                    href="<?= htmlspecialchars(
                        URL::to('monitor'),
                        ENT_QUOTES,
                        'UTF-8'
                    ) ?>"
                >
                    View Monitor
                </a>

            </p>

        </div>

    <?php else: ?>

        <div class="table-responsive">

            <table>

                <thead>

                    <tr>

                        <th>
                            ID
                        </th>

                        <th>
                            Customer
                        </th>

                        <th>
                            Device
                        </th>

                        <th>
                            Started
                        </th>

                        <th>
                            Resolved
                        </th>

                        <th>
                            Duration
                        </th>

                        <th>
                            Reason
                        </th>

                        <th>
                            Status
                        </th>

                        <th>
                            Actions
                        </th>

                    </tr>

                </thead>


                <tbody>

                <?php foreach ($incidents as $incident): ?>

                    <?php

                    $incidentId = (int) (
                        $incident['id']
                        ?? 0
                    );

                    $status = (string) (
                        $incident['status']
                        ?? 'unknown'
                    );

                    ?>

                    <tr>

                        <td>

                            #<?= $incidentId ?>

                        </td>


                        <td>

                            <?= htmlspecialchars(
                                (string) (
                                    $incident['company_name']
                                    ?? 'Unknown Customer'
                                ),
                                ENT_QUOTES,
                                'UTF-8'
                            ) ?>

                        </td>


                        <td>

                            <?= htmlspecialchars(
                                (string) (
                                    $incident['device_name']
                                    ?: 'Unnamed Device'
                                ),
                                ENT_QUOTES,
                                'UTF-8'
                            ) ?>

                            <?php if (
                                !empty(
                                    $incident['hostname']
                                )
                            ): ?>

                                <br>

                                <small>

                                    <?= htmlspecialchars(
                                        (string) $incident[
                                            'hostname'
                                        ],
                                        ENT_QUOTES,
                                        'UTF-8'
                                    ) ?>

                                </small>

                            <?php endif; ?>

                        </td>


                        <td>

                            <?= htmlspecialchars(
                                (string) (
                                    $incident['started_at']
                                    ?? '—'
                                ),
                                ENT_QUOTES,
                                'UTF-8'
                            ) ?>

                        </td>


                        <td>

                            <?= htmlspecialchars(
                                (string) (
                                    $incident['resolved_at']
                                    ?: 'Ongoing'
                                ),
                                ENT_QUOTES,
                                'UTF-8'
                            ) ?>

                        </td>


                        <td>

                            <?php if (
                                $incident[
                                    'duration_seconds'
                                ] !== null
                            ): ?>

                                <?= htmlspecialchars(
                                    (string) $incident[
                                        'duration_seconds'
                                    ],
                                    ENT_QUOTES,
                                    'UTF-8'
                                ) ?>

                                sec

                            <?php else: ?>

                                —

                            <?php endif; ?>

                        </td>


                        <td>

                            <?php if (
                                !empty(
                                    $incident['reason']
                                )
                            ): ?>

                                <?= htmlspecialchars(
                                    (string) $incident[
                                        'reason'
                                    ],
                                    ENT_QUOTES,
                                    'UTF-8'
                                ) ?>

                            <?php else: ?>

                                —

                            <?php endif; ?>

                        </td>


                        <td>

                            <?php if (
                                $status === 'open'
                            ): ?>

                                ● Open

                            <?php elseif (
                                $status === 'resolved'
                            ): ?>

                                ● Resolved

                            <?php else: ?>

                                ● Unknown

                            <?php endif; ?>

                        </td>


                        <td>

                            <a
                                href="<?= htmlspecialchars(
                                    URL::to(
                                        'incidents/'
                                        . $incidentId
                                    ),
                                    ENT_QUOTES,
                                    'UTF-8'
                                ) ?>"
                            >
                                View
                            </a>

                        </td>

                    </tr>

                <?php endforeach; ?>

                </tbody>

            </table>

        </div>

    <?php endif; ?>

</section>


<?php

$content = ob_get_clean();

require TEMPLATE_PATH
    . DS
    . 'layouts'
    . DS
    . 'app.php';